---
-   name: Check if swap file exists
    stat:
        path: "{{ swap_file_path }}"
    register: swap_file_check

-   name: Create swap file
    command: fallocate -l {{ swap_size }} {{ swap_file_path }}
    when: not swap_file_check.stat.exists

-   name: Set permissions on swap file
    file:
        path: "{{ swap_file_path }}"
        mode: 0600
    when: not swap_file_check.stat.exists

-   name: Make swap
    command: mkswap {{ swap_file_path }}
    when: not swap_file_check.stat.exists

-   name: Add swap to fstab
    lineinfile:
        dest: /etc/fstab
        regexp: "{{ swap_file_path }}"
        line: "{{ swap_file_path }} none swap sw 0 0"
    when: not swap_file_check.stat.exists

-   name: Turn on swap
    command: swapon -a
    when: not swap_file_check.stat.exists
